language: c

addons:
  apt:
    packages:
      - openmpi-bin
      - libopenmpi-dev
      - lcov
      - time

script:
    - export CXXFLAGS="-fprofile-arcs -ftest-coverage -Wno-write-strings  -Wall -Werror -Wno-unused-but-set-variable -Wno-unused-variable"
    - make -C example
    - timeout 600s make -C example test_check

after_success: 
    - bash <(curl -s https://codecov.io/bash)
